spring.datasource.url=jdbc:postgresql://localhost:5432/Company1
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
server.port=9996
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.authentication=TRACE
logging.level.org.springframework.security.web=TRACE
 